In [38]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [39]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [40]:
model = LinearRegression()
model.fit(df[['area']], df[['price']])
model.coef_, model.intercept_

(array([[135.78767123]]), array([180616.43835616]))

In [41]:
model.predict([[5000]])

D:\Anaconda__\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[859554.79452055]])

In [42]:
import pickle
with open('model_pickle', 'wb') as file:
    pickle.dump(model, file)

In [43]:
with open('model_pickle', 'rb') as file:
    mp = pickle.load(file)

In [44]:
mp.coef_, mp.intercept_

(array([[135.78767123]]), array([180616.43835616]))

In [45]:
mp.predict([[5000]])

D:\Anaconda__\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[859554.79452055]])

In [46]:
import joblib
joblib.dump(model, 'model_joblib')
mj = joblib.load('model_joblib')
mj.coef_, mj.intercept_

(array([[135.78767123]]), array([180616.43835616]))

In [47]:
mj.predict([[5000]])

D:\Anaconda__\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[859554.79452055]])